/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homelesshousingapp;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.io.*;
/**
 *
 * @author x17138752
 */
public class HomelessHousingGUI extends javax.swing.JFrame {

    /**
     * Creates new form HomelessHousingGUI
     */
    int i = 0;
    private ArrayList<AvailableHousing> Housing;
    ArrayList<AvailableHousing> log =new ArrayList();
    public HomelessHousingGUI() {
        initComponents();
        readFromFile();
        AvailableHousing a1 = new AvailableHousing("Phil","Stevenson","086 2678964","123 Redbrick Road","Finglas East","Dublin 11",3,14);
        AvailableHousing a2 = new AvailableHousing("Bob","Roe","085 12358710","34 Wall Road","Finglas North","Dublin 11",2,5);
        AvailableHousing a3 = new AvailableHousing("John","Williams","087 4537195","12 East Road","Ballygall Road East","Dublin 11",4,6);
        AvailableHousing a4 = new AvailableHousing("Sean","Nolan","085 6730991","8 Glasnevin Court","Cabra East","Dublin 11",2,8);
        AvailableHousing a5 = new AvailableHousing("Connor","Slyman","086 7896730","4 Westpark Drive","Glasnevin","Dublin 11",5,12);
        
        log.add(a1);
        log.add(a2);
        log.add(a3);
        log.add(a4);
        log.add(a5);
        
        Fname3TF.setText(log.get(i).getFname());
        Lname3TF.setText(log.get(i).getLname());
        Address1TF2.setText(log.get(i).getAddressLine1());
        Address2TF2.setText(log.get(i).getAddressLine2());
        Address3TF2.setText(log.get(i).getAddressLine3());
        NumRooms2TF.setText(Integer.toString(log.get(i).getNumRooms()));
        Duration2TF.setText(Integer.toString(log.get(i).getDuration()));
        contactNo3TF.setText(log.get(i).getContactNo());
        IDTF.setText(Integer.toString(i + 1));
        
    }//end HomelessHousingGUI

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomelessHousingJTP = new javax.swing.JTabbedPane();
        WelcomeJP = new javax.swing.JPanel();
        ImageLbl = new javax.swing.JLabel();
        Heading4Lbl = new javax.swing.JLabel();
        SubHeadLbl = new javax.swing.JLabel();
        AvailableJP = new javax.swing.JPanel();
        HeadingLbl = new javax.swing.JLabel();
        FnameLbl = new javax.swing.JLabel();
        LnameLbl = new javax.swing.JLabel();
        Address1Lbl = new javax.swing.JLabel();
        Address2Lbl = new javax.swing.JLabel();
        Address3Lbl = new javax.swing.JLabel();
        NumRoomsLbl = new javax.swing.JLabel();
        DurationLbl = new javax.swing.JLabel();
        contactNoLbl = new javax.swing.JLabel();
        FnameTF = new javax.swing.JTextField();
        LnameTF = new javax.swing.JTextField();
        Address1TF = new javax.swing.JTextField();
        Address3TF = new javax.swing.JTextField();
        NumRoomsTF = new javax.swing.JTextField();
        DurationTF = new javax.swing.JTextField();
        contactNoTF = new javax.swing.JTextField();
        SubmitBtn = new javax.swing.JButton();
        Address2TF = new javax.swing.JTextField();
        ApplyJP = new javax.swing.JPanel();
        Heading2Lbl1 = new javax.swing.JLabel();
        Fname2Lbl = new javax.swing.JLabel();
        Lname2Lbl = new javax.swing.JLabel();
        contactNo2Lbl = new javax.swing.JLabel();
        NumPeopleLbl = new javax.swing.JLabel();
        GenderLbl = new javax.swing.JLabel();
        dobLbl = new javax.swing.JLabel();
        Fname2TF = new javax.swing.JTextField();
        Lname2TF = new javax.swing.JTextField();
        contactNo2TF = new javax.swing.JTextField();
        NumPeopleTF = new javax.swing.JTextField();
        GenderTF = new javax.swing.JTextField();
        dobTF = new javax.swing.JTextField();
        Submit2Btn = new javax.swing.JButton();
        ID2Lbl = new javax.swing.JLabel();
        ID2TF = new javax.swing.JTextField();
        BrowseJP = new javax.swing.JPanel();
        Heading3Lbl = new javax.swing.JLabel();
        Fname3Lbl = new javax.swing.JLabel();
        Lname3Lbl = new javax.swing.JLabel();
        Address1Lbl2 = new javax.swing.JLabel();
        Address2Lbl2 = new javax.swing.JLabel();
        Address3Lbl2 = new javax.swing.JLabel();
        NumRooms2Lbl = new javax.swing.JLabel();
        Duration2Lbl = new javax.swing.JLabel();
        contactNo3Lbl = new javax.swing.JLabel();
        Fname3TF = new javax.swing.JTextField();
        Lname3TF = new javax.swing.JTextField();
        Address1TF2 = new javax.swing.JTextField();
        Address2TF2 = new javax.swing.JTextField();
        Address3TF2 = new javax.swing.JTextField();
        NumRooms2TF = new javax.swing.JTextField();
        Duration2TF = new javax.swing.JTextField();
        contactNo3TF = new javax.swing.JTextField();
        NextBtn = new javax.swing.JButton();
        PreviousBtn = new javax.swing.JButton();
        idLbl = new javax.swing.JLabel();
        IDTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ImageLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homelesshousingapp/cartoon-housing.jpg"))); // NOI18N

        Heading4Lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Heading4Lbl.setText("Welcome to Housing for the Homeless");

        SubHeadLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SubHeadLbl.setText("Browse and Apply for Available Housing");

        javax.swing.GroupLayout WelcomeJPLayout = new javax.swing.GroupLayout(WelcomeJP);
        WelcomeJP.setLayout(WelcomeJPLayout);
        WelcomeJPLayout.setHorizontalGroup(
            WelcomeJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeJPLayout.createSequentialGroup()
                .addGroup(WelcomeJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WelcomeJPLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(Heading4Lbl))
                    .addGroup(WelcomeJPLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(WelcomeJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SubHeadLbl)
                            .addComponent(ImageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        WelcomeJPLayout.setVerticalGroup(
            WelcomeJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeJPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Heading4Lbl)
                .addGap(18, 18, 18)
                .addComponent(ImageLbl)
                .addGap(18, 18, 18)
                .addComponent(SubHeadLbl)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        HomelessHousingJTP.addTab("Welcome", WelcomeJP);

        HeadingLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HeadingLbl.setText("Available Housing Form");

        FnameLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        FnameLbl.setText("First Name");

        LnameLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LnameLbl.setText("Last Name");

        Address1Lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Address1Lbl.setText("Address Line 1");

        Address2Lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Address2Lbl.setText("Address Line 2");

        Address3Lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Address3Lbl.setText("Address Line 3");

        NumRoomsLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NumRoomsLbl.setText("Number Of Rooms");

        DurationLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DurationLbl.setText("Duration (Days)");

        contactNoLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        contactNoLbl.setText("Contact Number");

        FnameTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        LnameTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Address1TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Address3TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        NumRoomsTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        DurationTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        contactNoTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        SubmitBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SubmitBtn.setText("Submit");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });

        Address2TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Address2TFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AvailableJPLayout = new javax.swing.GroupLayout(AvailableJP);
        AvailableJP.setLayout(AvailableJPLayout);
        AvailableJPLayout.setHorizontalGroup(
            AvailableJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AvailableJPLayout.createSequentialGroup()
                .addGroup(AvailableJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AvailableJPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AvailableJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(HeadingLbl)
                            .addGroup(AvailableJPLayout.createSequentialGroup()
                                .addGroup(AvailableJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FnameLbl)
                                    .addComponent(LnameLbl)
                                    .addComponent(Address1Lbl)
                                    .addComponent(Address2Lbl)
                                    .addComponent(Address3Lbl)
                                    .addComponent(NumRoomsLbl)
                                    .addComponent(DurationLbl)
                                    .addComponent(contactNoLbl))
                                .addGap(30, 30, 30)
                                .addGroup(AvailableJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LnameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(Address1TF)
                                    .addComponent(Address3TF)
                                    .addComponent(NumRoomsTF)
                                    .addComponent(DurationTF)
                                    .addComponent(contactNoTF)
                                    .addComponent(FnameTF)
                                    .addComponent(Address2TF)))))
                    .addGroup(AvailableJPLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        AvailableJPLayout.setVerticalGroup(
            AvailableJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AvailableJPLayout.createSequentialGroup()
                .addComponent(HeadingLbl)
                .addGap(18, 18, 18)
                .addGroup(AvailableJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FnameLbl)
                    .addComponent(FnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AvailableJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LnameLbl)
                    .addComponent(LnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AvailableJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address1Lbl)
                    .addComponent(Address1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AvailableJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address2Lbl)
                    .addComponent(Address2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AvailableJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address3Lbl)
                    .addComponent(Address3TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AvailableJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumRoomsLbl)
                    .addComponent(NumRoomsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AvailableJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DurationLbl)
                    .addComponent(DurationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AvailableJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNoLbl)
                    .addComponent(contactNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 67, Short.MAX_VALUE))
        );

        HomelessHousingJTP.addTab("Available", AvailableJP);

        Heading2Lbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Heading2Lbl1.setText("Looking for Housing Form");

        Fname2Lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Fname2Lbl.setText("First Name");

        Lname2Lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lname2Lbl.setText("Last Name");

        contactNo2Lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        contactNo2Lbl.setText("Contact Number");

        NumPeopleLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NumPeopleLbl.setText("Number of People");

        GenderLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        GenderLbl.setText("Gender");

        dobLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dobLbl.setText("Date of Birth");

        Fname2TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Lname2TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        contactNo2TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        NumPeopleTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        GenderTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        dobTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Submit2Btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Submit2Btn.setText("Submit");
        Submit2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit2BtnActionPerformed(evt);
            }
        });

        ID2Lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ID2Lbl.setText("Available ID");

        javax.swing.GroupLayout ApplyJPLayout = new javax.swing.GroupLayout(ApplyJP);
        ApplyJP.setLayout(ApplyJPLayout);
        ApplyJPLayout.setHorizontalGroup(
            ApplyJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApplyJPLayout.createSequentialGroup()
                .addGroup(ApplyJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ApplyJPLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(Heading2Lbl1))
                    .addGroup(ApplyJPLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(Submit2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ApplyJPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ApplyJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fname2Lbl)
                            .addComponent(Lname2Lbl)
                            .addComponent(contactNo2Lbl)
                            .addComponent(NumPeopleLbl)
                            .addComponent(GenderLbl)
                            .addComponent(dobLbl)
                            .addComponent(ID2Lbl))
                        .addGap(38, 38, 38)
                        .addGroup(ApplyJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Fname2TF, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(Lname2TF)
                            .addComponent(contactNo2TF)
                            .addComponent(NumPeopleTF)
                            .addComponent(GenderTF)
                            .addComponent(dobTF)
                            .addComponent(ID2TF))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        ApplyJPLayout.setVerticalGroup(
            ApplyJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApplyJPLayout.createSequentialGroup()
                .addComponent(Heading2Lbl1)
                .addGap(18, 18, 18)
                .addGroup(ApplyJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fname2Lbl)
                    .addComponent(Fname2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ApplyJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lname2Lbl)
                    .addComponent(Lname2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ApplyJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNo2Lbl)
                    .addComponent(contactNo2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ApplyJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumPeopleLbl)
                    .addComponent(NumPeopleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ApplyJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GenderLbl)
                    .addComponent(GenderTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ApplyJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dobLbl)
                    .addComponent(dobTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ApplyJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ID2Lbl)
                    .addComponent(ID2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(Submit2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 86, Short.MAX_VALUE))
        );

        HomelessHousingJTP.addTab("Apply", ApplyJP);

        Heading3Lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Heading3Lbl.setText("Available Housing Browse");

        Fname3Lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Fname3Lbl.setText("First Name");

        Lname3Lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lname3Lbl.setText("Last Name");

        Address1Lbl2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Address1Lbl2.setText("Address Line 1");

        Address2Lbl2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Address2Lbl2.setText("Address Line 2");

        Address3Lbl2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Address3Lbl2.setText("Address Line 3");

        NumRooms2Lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NumRooms2Lbl.setText("Number Of Rooms");

        Duration2Lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Duration2Lbl.setText("Duration (Days)");

        contactNo3Lbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        contactNo3Lbl.setText("Contact Number");

        Fname3TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Lname3TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Address1TF2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Address2TF2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Address3TF2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        NumRooms2TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Duration2TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        contactNo3TF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        NextBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NextBtn.setText("Next");
        NextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextBtnActionPerformed(evt);
            }
        });

        PreviousBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PreviousBtn.setText("Previous");
        PreviousBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousBtnActionPerformed(evt);
            }
        });

        idLbl.setText("ID");

        javax.swing.GroupLayout BrowseJPLayout = new javax.swing.GroupLayout(BrowseJP);
        BrowseJP.setLayout(BrowseJPLayout);
        BrowseJPLayout.setHorizontalGroup(
            BrowseJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BrowseJPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PreviousBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(NextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(BrowseJPLayout.createSequentialGroup()
                .addGroup(BrowseJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BrowseJPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(BrowseJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fname3Lbl)
                            .addComponent(Lname3Lbl)
                            .addComponent(Address1Lbl2)
                            .addComponent(Address2Lbl2)
                            .addComponent(Address3Lbl2)
                            .addComponent(NumRooms2Lbl)
                            .addComponent(Duration2Lbl)
                            .addComponent(contactNo3Lbl))
                        .addGap(30, 30, 30)
                        .addGroup(BrowseJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lname3TF, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(Address1TF2)
                            .addComponent(Address2TF2)
                            .addComponent(Address3TF2)
                            .addComponent(NumRooms2TF)
                            .addComponent(Duration2TF)
                            .addComponent(contactNo3TF)
                            .addComponent(Fname3TF)))
                    .addGroup(BrowseJPLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(Heading3Lbl)
                        .addGap(31, 31, 31)
                        .addComponent(idLbl)
                        .addGap(18, 18, 18)
                        .addComponent(IDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BrowseJPLayout.setVerticalGroup(
            BrowseJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BrowseJPLayout.createSequentialGroup()
                .addGroup(BrowseJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Heading3Lbl)
                    .addComponent(idLbl)
                    .addComponent(IDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BrowseJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fname3Lbl)
                    .addComponent(Fname3TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BrowseJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lname3Lbl)
                    .addComponent(Lname3TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BrowseJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address1Lbl2)
                    .addComponent(Address1TF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BrowseJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address2Lbl2)
                    .addComponent(Address2TF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BrowseJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address3Lbl2)
                    .addComponent(Address3TF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BrowseJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumRooms2Lbl)
                    .addComponent(NumRooms2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BrowseJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Duration2Lbl)
                    .addComponent(Duration2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BrowseJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNo3Lbl)
                    .addComponent(contactNo3TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BrowseJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PreviousBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        HomelessHousingJTP.addTab("Browse", BrowseJP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomelessHousingJTP)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomelessHousingJTP)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextBtnActionPerformed
        // TODO add your handling code here:
        if(i<log.size()-1){
            i++;
        }//end if
        else{
            i=0;
        }//end else         
        Fname3TF.setText(log.get(i).getFname());
        Lname3TF.setText(log.get(i).getLname());
        Address1TF2.setText(log.get(i).getAddressLine1());
        Address2TF2.setText(log.get(i).getAddressLine2());
        Address3TF2.setText(log.get(i).getAddressLine3());
        NumRooms2TF.setText(Integer.toString(log.get(i).getNumRooms()));
        Duration2TF.setText(Integer.toString(log.get(i).getDuration()));
        contactNo3TF.setText(log.get(i).getContactNo());
        IDTF.setText(Integer.toString(i + 1));
    }//GEN-LAST:event_NextBtnActionPerformed

    private void PreviousBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousBtnActionPerformed
        // TODO add your handling code here:
        if (i > 0) {
            i--;
        } else {
            i = 0;
        }        
        Fname3TF.setText(log.get(i).getFname());
        Lname3TF.setText(log.get(i).getLname());
        Address1TF2.setText(log.get(i).getAddressLine1());
        Address2TF2.setText(log.get(i).getAddressLine2());
        Address3TF2.setText(log.get(i).getAddressLine3());
        NumRooms2TF.setText(Integer.toString(log.get(i).getNumRooms()));
        Duration2TF.setText(Integer.toString(log.get(i).getDuration()));
        contactNo3TF.setText(log.get(i).getContactNo());
        IDTF.setText(Integer.toString(i + 1));
    }//GEN-LAST:event_PreviousBtnActionPerformed

    private void Submit2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit2BtnActionPerformed
        // TODO add your handling code here:
        BufferedWriter bw = null;
        LookingForHouse h = new LookingForHouse("","","",1,"","",1);
        h.setFname(Fname2TF.getText());
        h.setLname(Lname2TF.getText());
        h.setContactNo(contactNo2TF.getText());
        h.setNumPeople(Integer.parseInt(NumPeopleTF.getText()));
        h.setGender(GenderTF.getText());
        h.setDob(dobTF.getText());
        h.setID(Integer.parseInt(ID2TF.getText()));
        try{

	File file = new File("Looking.doc");
	  if (!file.exists()) {
	     file.createNewFile();
	  }//end if
	  FileWriter fw = new FileWriter(file);
	  bw = new BufferedWriter(fw);
	  bw.write(h.toString());
          JOptionPane.showMessageDialog(null,"Your details have been saved. Thank you");

      }//end try 
      catch (IOException ioe) {
	   ioe.printStackTrace();
	}//end catch
	finally{ 
	   try{
	      if(bw!=null){
		 bw.close();
              }//end if
	   }//end try
           catch(Exception ex){
	       JOptionPane.showMessageDialog(null,"Error"+ex);
	    }//end catch
	}//end finally
    }//GEN-LAST:event_Submit2BtnActionPerformed

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:
        BufferedWriter bw = null;
        AvailableHousing h;
        h = new AvailableHousing("","","","","","",1,1);
        h.setFname(FnameTF.getText());
        h.setLname(LnameTF.getText());
        h.setContactNo(contactNoTF.getText());
        h.setAddressLine1(Address1TF.getText());
        //h.setAddressLine2(Address2TF.getText());
        h.setAddressLine3(Address3TF.getText());
        h.setNumRooms(Integer.parseInt(NumRoomsTF.getText()));
        h.setDuration(Integer.parseInt(DurationTF.getText()));
        h.<AvailableHousing>setAddressLine2(Address2TF.getText());
        log.add(h);
        JOptionPane.showMessageDialog(null,h.toString());

	try{
	 File file = new File("Available.doc");
	 if (!file.exists()) {
            file.createNewFile();
	 }//end if
	 FileWriter fw = new FileWriter(file);
	 bw = new BufferedWriter(fw);
	 bw.write(h.toString());
         JOptionPane.showMessageDialog(null,"Your details have been saved. Thank you");
        }//end try 
        catch (IOException ioe) {
            ioe.printStackTrace();
	}//end catch
	finally{ 
	   try{
	      if(bw!=null){
		 bw.close();
              }//end if
	   }//end try
           catch(Exception ex){
	       JOptionPane.showMessageDialog(null,"Error"+ex);
	    }//end catch
	}//end finally
        
        
          
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void Address2TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Address2TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Address2TFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomelessHousingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomelessHousingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomelessHousingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomelessHousingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomelessHousingGUI().setVisible(true);
            }
        });
    }

    private void readFromFile() {
        try {
            File f = new File("browse.txt");
            FileInputStream fStream = new FileInputStream(f);
            ObjectInputStream oStream = new ObjectInputStream(fStream);

            Housing = (ArrayList<AvailableHousing>) oStream.readObject();
            oStream.close();
        } 
        catch (IOException | ClassNotFoundException ex) {
            System.out.println(ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address1Lbl;
    private javax.swing.JLabel Address1Lbl2;
    private javax.swing.JTextField Address1TF;
    private javax.swing.JTextField Address1TF2;
    private javax.swing.JLabel Address2Lbl;
    private javax.swing.JLabel Address2Lbl2;
    private javax.swing.JTextField Address2TF;
    private javax.swing.JTextField Address2TF2;
    private javax.swing.JLabel Address3Lbl;
    private javax.swing.JLabel Address3Lbl2;
    private javax.swing.JTextField Address3TF;
    private javax.swing.JTextField Address3TF2;
    private javax.swing.JPanel ApplyJP;
    private javax.swing.JPanel AvailableJP;
    private javax.swing.JPanel BrowseJP;
    private javax.swing.JLabel Duration2Lbl;
    private javax.swing.JTextField Duration2TF;
    private javax.swing.JLabel DurationLbl;
    private javax.swing.JTextField DurationTF;
    private javax.swing.JLabel Fname2Lbl;
    private javax.swing.JTextField Fname2TF;
    private javax.swing.JLabel Fname3Lbl;
    private javax.swing.JTextField Fname3TF;
    private javax.swing.JLabel FnameLbl;
    private javax.swing.JTextField FnameTF;
    private javax.swing.JLabel GenderLbl;
    private javax.swing.JTextField GenderTF;
    private javax.swing.JLabel Heading2Lbl1;
    private javax.swing.JLabel Heading3Lbl;
    private javax.swing.JLabel Heading4Lbl;
    private javax.swing.JLabel HeadingLbl;
    private javax.swing.JTabbedPane HomelessHousingJTP;
    private javax.swing.JLabel ID2Lbl;
    private javax.swing.JTextField ID2TF;
    private javax.swing.JTextField IDTF;
    private javax.swing.JLabel ImageLbl;
    private javax.swing.JLabel Lname2Lbl;
    private javax.swing.JTextField Lname2TF;
    private javax.swing.JLabel Lname3Lbl;
    private javax.swing.JTextField Lname3TF;
    private javax.swing.JLabel LnameLbl;
    private javax.swing.JTextField LnameTF;
    private javax.swing.JButton NextBtn;
    private javax.swing.JLabel NumPeopleLbl;
    private javax.swing.JTextField NumPeopleTF;
    private javax.swing.JLabel NumRooms2Lbl;
    private javax.swing.JTextField NumRooms2TF;
    private javax.swing.JLabel NumRoomsLbl;
    private javax.swing.JTextField NumRoomsTF;
    private javax.swing.JButton PreviousBtn;
    private javax.swing.JLabel SubHeadLbl;
    private javax.swing.JButton Submit2Btn;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JPanel WelcomeJP;
    private javax.swing.JLabel contactNo2Lbl;
    private javax.swing.JTextField contactNo2TF;
    private javax.swing.JLabel contactNo3Lbl;
    private javax.swing.JTextField contactNo3TF;
    private javax.swing.JLabel contactNoLbl;
    private javax.swing.JTextField contactNoTF;
    private javax.swing.JLabel dobLbl;
    private javax.swing.JTextField dobTF;
    private javax.swing.JLabel idLbl;
    // End of variables declaration//GEN-END:variables
}
